build-prod:
	odin build . -out:../build/game.exe -show-timings -o:speed

build:
	odin build . -out:../build/game.exe -debug -show-timings -terse-errors -o:none

build-speed:
	odin build . -out:../build/game.exe -show-timings -o:speed

build-aggressive:
	odin build . -out:../build/game.exe -show-timings -o:aggressive

run:
	odin run . -out:../build/game.exe -debug -show-timings -terse-errors -o:none

clean:
	rm ../build/
